export enum UserDomainExceptionCodes {
  DoesNotExist = 'USER.DOES_NOT_EXIST',
  AlreadyExists = 'USER.ALREADY_EXISTS',
  FullNameDoesNotValid = 'USER.FULL_NAME_DOES_NOT_VALID',
  UsernameAlreadyExists = 'USER.USER_NAME_ALREADY_EXISTS',
  AddressDoesNotValid = 'USER.ADDRESS_DOES_NOT_VALID',
  IdDoesNotValid = 'USER.ID_DOES_NOT_VALID',
  EmailAlreadyExists = 'USER.EMAIL_ALREADY_EXISTS',
  EmailDoesNotExist = 'USER.EMAIL_DOES_NOT_EXIST',
  RoleDoesNotValid = 'USER.ROLE_DOES_NOT_VALID',
  UsernameDoesNotValid = 'USER.NAME_DOES_NOT_VALID',
  EmailDoesNotValid = 'USER.EMAIL_DOES_NOT_VALID',
  PasswordDoesNotValid = 'USER.PASSWORD_DOES_NOT_VALID',
  CredentialDoesNotValid = 'USER.CREDENTIAL_DOES_NOT_VALID',
}
